language: python
dist: xenial # needed for python 3.7

cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"

matrix:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
      services:
        - docker
        
stages:
  # - build
  - name: test
    if: type IN (push, pull_request) AND branch = master
  - name: release
    if: tag IS present

jobs:
  include:
    - stage: release
      python: 3.7
      name: "Release current repository as Docker Image."
      before_install:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker pull $DOCKER_USERNAME/$DOCKER_IMAGE_TAG:latest || true
      install:
        - docker build --cache-from $DOCKER_USERNAME/$DOCKER_IMAGE_TAG:latest --tag $DOCKER_USERNAME/$DOCKER_IMAGE_TAG:latest --tag $DOCKER_USERNAME/$DOCKER_IMAGE_TAG:$TRAVIS_TAG .
      script:
        - docker push $DOCKER_USERNAME/$DOCKER_IMAGE_TAG:latest
        - docker push $DOCKER_USERNAME/$DOCKER_IMAGE_TAG:$TRAVIS_TAG

script:
  - echo "Run Tests here"