language: python
dist: xenial # needed for python 3.7
python:
  - "3.5"
  - "3.6"
  - "3.7"

stages:
  # - build
  - name: test
    if: type IN (push, pull_request) AND branch = master
  - name: release
    if: tag IS present

cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"

script:
  - python -m unittest discover -s tests -p "test_*.py"
  - pytest --cov dooralert/ --cov-report term

after_success:
  - codecov

jobs:
  include:
    - stage: release
      python: 3.7
      services:
        - docker
      name: "Release current repository as Docker Image."
      before_install:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker pull $DOCKER_USERNAME/$DOCKER_IMAGE_TAG:latest || true
      install:
        - docker build --cache-from $DOCKER_USERNAME/$DOCKER_IMAGE_TAG:latest --tag $DOCKER_USERNAME/$DOCKER_IMAGE_TAG:latest --tag $DOCKER_USERNAME/$DOCKER_IMAGE_TAG:$TRAVIS_TAG .
      script:
        - docker push $DOCKER_USERNAME/$DOCKER_IMAGE_TAG:latest
        - docker push $DOCKER_USERNAME/$DOCKER_IMAGE_TAG:$TRAVIS_TAG
